-optimizations aggressive
-optimizationpasses 5
-allowaccessmodification
-dontskipnonpubliclibraryclasses
-repackageclasses ''
-mergeinterfacesaggressively
-overloadaggressively
-dontpreverify
-verbose